# Generated by Django 4.1.2 on 2022-10-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.FileField(upload_to="static/images/todos/")),
                ("titre", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("isCompleted", models.BooleanField(default=False)),
            ],
        ),
    ]
